#!/usr/bin/env python3
"""
Embed the PWA (the files in ../web) into a single C++ header, web_assets.h,
as PROGMEM byte arrays. The firmware serves these straight from flash, so the
bridge is one self-contained sketch with no filesystem upload step.

Run from anywhere:  python3 tools/gen_web_assets.py
(output is written to esp32-bridge/web_assets.h)
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
WEB = os.path.join(PROJ, "web")
OUT = os.path.join(PROJ, "web_assets.h")

# Files to embed and the URL path each is served at. The service worker and
# manifest expect these exact paths.
ASSETS = [
    ("index.html",          "/index.html",          "text/html; charset=utf-8"),
    ("style.css",           "/style.css",            "text/css; charset=utf-8"),
    ("app.js",              "/app.js",               "text/javascript; charset=utf-8"),
    ("sw.js",               "/sw.js",                "text/javascript; charset=utf-8"),
    ("manifest.webmanifest","/manifest.webmanifest", "application/manifest+json"),
    ("icon-192.png",        "/icon-192.png",         "image/png"),
    ("icon-512.png",        "/icon-512.png",         "image/png"),
]


def c_array(name, data):
    out = ["static const uint8_t %s[] PROGMEM = {" % name]
    line = "  "
    for i, b in enumerate(data):
        line += "0x%02x," % b
        if (i + 1) % 16 == 0:
            out.append(line)
            line = "  "
    if line.strip():
        out.append(line)
    out.append("};")
    return "\n".join(out)


def main():
    parts = [
        "// AUTO-GENERATED by tools/gen_web_assets.py — do not edit by hand.",
        "// Regenerate after changing anything in web/ :  python3 tools/gen_web_assets.py",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    table = []
    for idx, (fname, path, mime) in enumerate(ASSETS):
        fpath = os.path.join(WEB, fname)
        with open(fpath, "rb") as f:
            data = f.read()
        sym = "asset_%d" % idx
        parts.append("// %s  (%d bytes)" % (fname, len(data)))
        parts.append(c_array(sym, data))
        parts.append("")
        table.append((path, mime, sym, len(data)))

    parts.append("struct WebAsset {")
    parts.append("  const char *path;")
    parts.append("  const char *mime;")
    parts.append("  const uint8_t *data;")
    parts.append("  size_t len;")
    parts.append("};")
    parts.append("")
    parts.append("static const WebAsset WEB_ASSETS[] = {")
    for path, mime, sym, ln in table:
        parts.append('  { "%s", "%s", %s, %d },' % (path, mime, sym, ln))
    parts.append("};")
    parts.append("static const size_t WEB_ASSETS_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);")
    parts.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    total = sum(ln for _, _, _, ln in table)
    print("wrote %s  (%d assets, %d bytes embedded)" % (OUT, len(table), total))


if __name__ == "__main__":
    main()
