#!/usr/bin/env bash
#
# Generate an iOS-trustable self-signed TLS cert for the ESP32 bridge and emit
# cert.h (DER byte arrays the firmware embeds), plus lg-bridge.crt to install
# and trust on your iPhone.
#
# iOS is picky about certs it will trust:
#   - must carry a Subject Alternative Name (SAN) matching how you reach it
#     (the ESP32's IP address, and a <name>.local mDNS name)
#   - RSA 2048, SHA-256
#   - validity <= 398 days
# This script produces exactly that.
#
# Usage:
#   ./make_cert.sh <esp32-ip> [mdns-name]
# Example:
#   ./make_cert.sh 192.168.1.60 lgbridge
#       -> reachable at https://192.168.1.60  and  https://lgbridge.local
#
set -euo pipefail

IP="${1:-}"
MDNS="${2:-lgbridge}"
if [[ -z "$IP" ]]; then
  echo "usage: $0 <esp32-ip> [mdns-name]" >&2
  exit 1
fi

HERE="$(cd "$(dirname "$0")" && pwd)"
PROJ="$(dirname "$HERE")"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

cat > "$TMP/openssl.cnf" <<EOF
[req]
distinguished_name = dn
x509_extensions = v3
prompt = no
[dn]
CN = LG Remote Bridge
O  = lg-remote-pwa
[v3]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt
[alt]
IP.1  = ${IP}
DNS.1 = ${MDNS}.local
EOF

echo "Generating RSA-2048 / SHA-256 self-signed cert for ${IP} and ${MDNS}.local ..."
openssl req -x509 -nodes -newkey rsa:2048 -sha256 -days 397 \
  -keyout "$TMP/server.key" -out "$TMP/server.crt" \
  -config "$TMP/openssl.cnf" >/dev/null 2>&1

# DER forms for the firmware (mbedTLS in esp32_https_server parses DER).
openssl x509 -in "$TMP/server.crt" -outform der -out "$TMP/server.crt.der"
openssl rsa  -in "$TMP/server.key" -outform der -out "$TMP/server.key.der" 2>/dev/null

emit_array () { # name file
  local name="$1" file="$2"
  echo "static const uint8_t ${name}[] PROGMEM = {"
  # Portable byte dump (no xxd dependency): one "0xNN," per byte.
  od -An -v -tx1 "$file" | tr -s ' \t' '\n' | grep -E '^[0-9a-fA-F]{2}$' \
    | sed 's/^/  0x/; s/$/,/'
  echo "};"
  echo "static const size_t ${name}_len = $(wc -c < "$file" | tr -d ' ');"
  echo
}

{
  echo "// AUTO-GENERATED by tools/make_cert.sh — DO NOT COMMIT (contains a private key)."
  echo "// Cert valid for IP ${IP} and ${MDNS}.local, ~397 days from $(date +%Y-%m-%d)."
  echo "#pragma once"
  echo "#include <Arduino.h>"
  echo
  emit_array "CERT_DER" "$TMP/server.crt.der"
  emit_array "PKEY_DER" "$TMP/server.key.der"
} > "$PROJ/cert.h"

# The cert to install on the iPhone (DER .crt opens cleanly in iOS).
cp "$TMP/server.crt.der" "$PROJ/lg-bridge.crt"

echo
echo "Wrote:"
echo "  $PROJ/cert.h        (embedded in the sketch — git-ignored, keep private)"
echo "  $PROJ/lg-bridge.crt (AirDrop/email this to your iPhone and trust it)"
echo
echo "On the iPhone: open lg-bridge.crt -> install the profile (Settings > Profile"
echo "Downloaded), then Settings > General > About > Certificate Trust Settings ->"
echo "enable full trust for 'LG Remote Bridge'."
